// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#include common_scripts\utility;
#include maps\mp\_utility;

main()
{
    level.tweakfile = 1;
    setdvar( "r_rimIntensity_debug", 1 );
    setdvar( "r_rimIntensity", 15 );
}
