// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include maps\mp\_utility;
#include maps\mp\gametypes_zm\_hud_util;
#include common_scripts\utility;
#include maps\mp\zombies\_zm_utility;
#include maps\mp\gametypes_zm\_zm_gametype;
#include maps\mp\zombies\_zm_stats;
#include maps\mp\zombies\_zm_ai_dogs;
#include maps\mp\zombies\_zm;

#include maps\mp\zombies\_zm_magicbox;

main()
{
	maps\mp\gametypes_zm\_zm_gametype::main();
	level.onprecachegametype = ::onprecachegametype;
	level.onstartgametype = ::onstartgametype;
	level._game_module_custom_spawn_init_func = maps\mp\gametypes_zm\_zm_gametype::custom_spawn_init_func;
	level._game_module_stat_update_func = maps\mp\zombies\_zm_stats::survival_classic_custom_stat_update;
}

onprecachegametype()
{
	level.playersuicideallowed = 1;
	level.canplayersuicide = ::canplayersuicide;
	level.suicide_weapon = "death_self_zm";
	precacheitem( "death_self_zm" );
	if ( isdefined( level.precachecustomcharacters ) )
		level [[ level.precachecustomcharacters ]]();
}

onstartgametype()
{
	maps\mp\gametypes_zm\_zm_gametype::setup_standard_objects( level.default_start_location );
	maps\mp\gametypes_zm\_zm_gametype::setup_classic_gametype();
	level thread zclassic_main();
}

zclassic_main()
{
	flag_wait( "start_zombie_round_logic" );
	level thread maps\mp\zombies\_zm::round_start();
}